// Auto-generated from official roll lists (20SWE & 21SWE, 8th Semester).
// To add future batches, append entries here or enter them in the CMS.

export interface AlumnusRecord {
  roll: string;
  name: string;
  batch: string;
}

export const ALUMNI_RECORDS: AlumnusRecord[] = [
  { roll: "20SW01", name: "Mr. Abdullah", batch: "20SWE" },
  { roll: "20SW02", name: "Ms. Hina Arain", batch: "20SWE" },
  { roll: "20SW03", name: "Ms. Amara", batch: "20SWE" },
  { roll: "20SW04", name: "Ms. Yamna Ali", batch: "20SWE" },
  { roll: "20SW06", name: "Mr. Muhammad Usman", batch: "20SWE" },
  { roll: "20SW07", name: "Mr. Abdul Fatah", batch: "20SWE" },
  { roll: "20SW08", name: "Ms. Amna Gul", batch: "20SWE" },
  { roll: "20SW09", name: "Mr. Suhail Ahmed", batch: "20SWE" },
  { roll: "20SW10", name: "Mr. Ali Abbas", batch: "20SWE" },
  { roll: "20SW11", name: "Mr. Faraz Ahmed", batch: "20SWE" },
  { roll: "20SW12", name: "Mr. Ashir Ali", batch: "20SWE" },
  { roll: "20SW13", name: "Mr. Shahzad Ahmed", batch: "20SWE" },
  { roll: "20SW14", name: "Ms. Aqsa / Isha", batch: "20SWE" },
  { roll: "20SW15", name: "Ms. Sana", batch: "20SWE" },
  { roll: "20SW16", name: "Ms. Sheema Zain", batch: "20SWE" },
  { roll: "20SW17", name: "Mr. Tayab U Rehman", batch: "20SWE" },
  { roll: "20SW18", name: "Mr. Abdul Kareem", batch: "20SWE" },
  { roll: "20SW19", name: "Mr. Zeeshan Ali Alias Adeel", batch: "20SWE" },
  { roll: "20SW20", name: "Mr. Mubashir Najam", batch: "20SWE" },
  { roll: "20SW21", name: "Mr. Abdul Razzaque", batch: "20SWE" },
  { roll: "20SW22", name: "Mr. Ahmar Mobeen", batch: "20SWE" },
  { roll: "20SW23", name: "Ms. Masooma", batch: "20SWE" },
  { roll: "20SW24", name: "Mr. Muhammad Usman", batch: "20SWE" },
  { roll: "20SW25", name: "Mr. Abdul Samad", batch: "20SWE" },
  { roll: "20SW26", name: "Mr. Qamar Raza", batch: "20SWE" },
  { roll: "20SW27", name: "Ms. Durriya Roha", batch: "20SWE" },
  { roll: "20SW28", name: "Mr. Pirshotam Parmar", batch: "20SWE" },
  { roll: "20SW29", name: "Mr. Shaeel Ahmed", batch: "20SWE" },
  { roll: "20SW30", name: "Ms. Aliya", batch: "20SWE" },
  { roll: "20SW31", name: "Mr. Majid Ali", batch: "20SWE" },
  { roll: "20SW32", name: "Mr. Kashif Ali", batch: "20SWE" },
  { roll: "20SW33", name: "Ms. Malaika", batch: "20SWE" },
  { roll: "20SW34", name: "Mr. Abdul Hayee", batch: "20SWE" },
  { roll: "20SW35", name: "Mr. Jawad Hussain", batch: "20SWE" },
  { roll: "20SW36", name: "Ms. Khadija", batch: "20SWE" },
  { roll: "20SW37", name: "Mr. Ishfaque Hussain", batch: "20SWE" },
  { roll: "20SW38", name: "Mr. Fardeen Saeed", batch: "20SWE" },
  { roll: "20SW39", name: "Mr. Faraz Ahmed", batch: "20SWE" },
  { roll: "20SW40", name: "Mr. Ali Hyder", batch: "20SWE" },
  { roll: "20SW41", name: "Mr. Muhammad Moinuddin", batch: "20SWE" },
  { roll: "20SW42", name: "Mr. Mukhtiar Ahmed", batch: "20SWE" },
  { roll: "20SW43", name: "Ms. Mahnoor", batch: "20SWE" },
  { roll: "20SW44", name: "Mr. Lajpat", batch: "20SWE" },
  { roll: "20SW45", name: "Mr. Driodhan", batch: "20SWE" },
  { roll: "20SW46", name: "Mr. Saleemullah", batch: "20SWE" },
  { roll: "20SW47", name: "Ms. Murk", batch: "20SWE" },
  { roll: "20SW48", name: "Mr. Mashood Hussain", batch: "20SWE" },
  { roll: "21SW01", name: "Mr. Aamir Ali", batch: "21SWE" },
  { roll: "21SW02", name: "Ms. Jaweria", batch: "21SWE" },
  { roll: "21SW03", name: "Ms. Bisma", batch: "21SWE" },
  { roll: "21SW04", name: "Ms. Mehwish", batch: "21SWE" },
  { roll: "21SW05", name: "Mr. Shahzaman Ali", batch: "21SWE" },
  { roll: "21SW07", name: "Mr. Abdul Wahab", batch: "21SWE" },
  { roll: "21SW08", name: "Ms. Asheena Fazal Alias Bibi", batch: "21SWE" },
  { roll: "21SW09", name: "Mr. Barkat Ali", batch: "21SWE" },
  { roll: "21SW10", name: "Ms. Humera", batch: "21SWE" },
  { roll: "21SW11", name: "Ms. Hakim", batch: "21SWE" },
  { roll: "21SW12", name: "Mr. Abdul Hameed", batch: "21SWE" },
  { roll: "21SW14", name: "Mr. Faisal Rahman", batch: "21SWE" },
  { roll: "21SW15", name: "Mr. Nawab Ali", batch: "21SWE" },
  { roll: "21SW17", name: "Mr. Muhammad Faraz", batch: "21SWE" },
  { roll: "21SW18", name: "Mr. Amjad Ali", batch: "21SWE" },
  { roll: "21SW19", name: "Mr. Ahsan Ali", batch: "21SWE" },
  { roll: "21SW20", name: "Mr. Mujtaba Ali", batch: "21SWE" },
  { roll: "21SW23", name: "Mr. Muzamil Javed", batch: "21SWE" },
  { roll: "21SW24", name: "Mr. Sajid Ali", batch: "21SWE" },
  { roll: "21SW25", name: "Ms. Noor Fatima", batch: "21SWE" },
  { roll: "21SW26", name: "Mr. Ahrar Ali", batch: "21SWE" },
  { roll: "21SW27", name: "Mr. Altaf Ali", batch: "21SWE" },
  { roll: "21SW28", name: "Mr. Muhammad Ishaque", batch: "21SWE" },
  { roll: "21SW29", name: "Mr. Sheraz Hussain", batch: "21SWE" },
  { roll: "21SW30", name: "Mr. Inamullah", batch: "21SWE" },
  { roll: "21SW32", name: "Mr. Amjad Hussain", batch: "21SWE" },
  { roll: "21SW33", name: "Mr. Muhammad Muzammil", batch: "21SWE" },
  { roll: "21SW34", name: "Mr. Aurangzaib Khan", batch: "21SWE" },
  { roll: "21SW35", name: "Mr. Haris", batch: "21SWE" },
  { roll: "21SW36", name: "Ms. Maria Ziia", batch: "21SWE" },
  { roll: "21SW37", name: "Mr. Muhammad Umer", batch: "21SWE" },
  { roll: "21SW38", name: "Ms. Areeba", batch: "21SWE" },
  { roll: "21SW39", name: "Mr. Abdul Baqi", batch: "21SWE" },
  { roll: "21SW40", name: "Mr. Aizaz Tarique Bashir", batch: "21SWE" },
  { roll: "21SW41", name: "Mr. Ghulam Qadir", batch: "21SWE" },
  { roll: "21SW42", name: "Mr. Jameel Ahmed", batch: "21SWE" },
  { roll: "21SW43", name: "Mr. Bhaveendar Singh", batch: "21SWE" },
  { roll: "21SW44", name: "Mr. Azhar U Ddin", batch: "21SWE" },
  { roll: "21SW45", name: "Ms. Asma", batch: "21SWE" },
  { roll: "21SW46", name: "Mr. Muhammad Hashim", batch: "21SWE" },
  { roll: "21SW48", name: "Ms. Muqadas", batch: "21SWE" },
  { roll: "21SW49", name: "Mr. Nazakat", batch: "21SWE" },
  { roll: "21SW50", name: "Mr. Umaid Ali", batch: "21SWE" },
  { roll: "21SW51", name: "Mr. Muhammad Asim", batch: "21SWE" },
  { roll: "21SW52", name: "Mr. Muzamil Mehboob", batch: "21SWE" },
  { roll: "21SW53", name: "Mr. Fazal Hadi", batch: "21SWE" },
];